### PR TITLE
Add custom resolution option and replace if statements with case

### PR DESCRIPTION
**Pull request by ghost**
Currently untested but added custom resolution option

### CODE REVIEW

**Comment by GabubuAvailable** [comment]
image
maybe try before pulling request?
EDIT: you forgot the "}"

**Comment by GabubuAvailable** [comment]
and the "custom resolution" option doesn't work
image
that's the output when selecting

**Comment by ghost** [comment]
hopefully these will do, i think
also added refresh rate option since not everyone has a 60hz monitor

**Comment by GabubuAvailable** [comment]
testing now

**Comment by GabubuAvailable** [comment]
finally i can merge now :)
thanks for pr

**Pull request merged**
